# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Vnc0d9r
email: vnc0d9r@gmail.com

#write html inside the double quotes to display in jumbotron
description: "<h1>Vnc0d9r</h1><h3>Awesome Hacking Tutorial for everyone</h3>Hope you like it!"

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://vnc0d9r.github.io" # the base hostname & protocol for your site
twitter_username: vnc0d9r
github_username:  vnc0d9r

# Build settings
markdown: kramdown
